### ISSUE TITLE
Support async input

### ISSUE THREAD

**Issue by erf** [timsneath/dart_console#10]
I'd like to read input async, so that i can have a game loop going, without locking up the loop waiting for input.

Is this something you think is possible to implement or you'd like to add?

**Comment by timsneath** [comment]
I'd be very happy to see a contribution of this kind! I have a number of ideas for this package, but it's very much a "weekends and evenings" project / labor of love, so I'd be delighted to see others join in the fun. Would you be interested in working on this feature?

**Comment by erf** [comment]
I'd like to help, but not very familiar with the low level stuff and streams right now. I did try to find a way to read from stdio asynchronously, you have the the `stdio.listen` function, but it seem to close after first event. Do you know how i can keep listening to those events?

Also, do you know if it is possible to debug console apps from Android Studio?

**Comment by timsneath** [comment]
## Implementing async input
I'd also need to do some research on this front. I know on VT-style terminals, you can "read with a timeout" and set that timeout (see the `VMIN` and `VTIME` constants in https://github.com/timsneath/dart_console/blob/master/lib/src/ffi/unix/termios.dart). If there's something in the stream, I assume it would stay there until the next read? 

There's some interesting commentary here: https://github.com/flutter/flutter/issues/10677 that suggests that this is doable so long as there aren't other subscribers to `stdin`, which seems to be the case in this scenario. 

## Debugging console apps from Android Studio
I don't know about this, I'm afraid. I think IntelliJ provides the means for this, but whether this is exposed from Android Studio, I don't know. I use Visual Studio Code for writing this library, which is very capable and supports debugging. 

## Comparing to DirectMyFile
I originally looked at their library and even contributed a fix or two. They've built something useful, however it's higher-level than `dart_console` and exclusively uses VT terminal escape sequences, which can be restrictive if you want to build something that works on Windows or sets attributes that aren't available in that way (e.g. disabling Ctrl+C). 

[Dart FFI](https://dart.dev/guides/libraries/c-interop) is a new feature in Dart 2.6 that provides a lower-level approach where you can make system calls, and `dart_console` uses FFI for methods like `enableRawMode()`. I wanted the chance to try FFI out, and this was a perfect marriage of convenience and interest!

**Comment by erf** [comment]
I did not know that the terminal would limit how you read input.. Hmm.. I would like to preferably read all characters until the end of the program or until i don't want to listen any more, but maybe that's not possible..? I did look at the comments in that Flutter issue, but not sure what to do with that.

I'm able to setup a run configuration for a Dart console app in Android Studio, but not sure how i launch and debug the terminal. Is it easy to set this up in VS Code?

I like that you seem to keep this library minimal, and with Dart FFI it's possible to do more!

**Comment by erf** [comment]
I seem to be able to do async IO using `stdin.listen`, i think the problem occur when you try to do both sync and async io, as stated [here](https://api.dartlang.org/stable/2.6.1/dart-io/Stdin-class.html):
> Mixing synchronous and asynchronous reads is undefined.

I made an `async.dart` example in a branch [here](https://github.com/erf/dart_console/commit/e89366d1fe3ff6e6d721d3a56bf8137da0ab7a13).

Notice if you set `rawmode=false` inside the `listen` callback, you will end the stream. I think that is because the `rawmode` setter does some sync io.

Should i try to build a `Console.readKeyAsync` based on the `async.dart` example ?

**Comment by erf** [comment]
I added a new commit to that branch with a minimal async example. 

I also added `unitType` to key. Also would it make sense to simplify `readKey`, so that the control characters could be figured out later, perhaps by adding getters to it?

**Comment by erf** [comment]
Maybe this [nonBlocking](https://api.dartlang.org/stable/2.6.1/dart-io/Stdout/nonBlocking.html) is needed for non-blocking io.

Also [writeCharCode](https://api.dartlang.org/stable/2.6.1/dart-io/Stdout/writeCharCode.html) might be a cool API addition.
