### ISSUE TITLE
Support window resize events 

### ISSUE THREAD

**Issue by erf** [timsneath/dart_console#11]
I'd like to suggest adding an API for a callback for windows resize event.

If you for example are building a text editor, you'd like to redraw content on resize.

**Comment by erf** [comment]
I'm looking into this.

**Comment by erf** [comment]
How would i map this function pointer using FFI ?

```
import 'dart:ffi';
import 'dart:io';

// typedef void (*sighandler_t)(int);
// sighandler_t signal(int signum, sighandler_t handler);

typedef signalNative = Int32 Function(Int32, Function);
typedef signalDart = int Function(int, Function);

const SIGWINCH = 28;
```

**Comment by erf** [comment]
Started working on resize related stuff in [this branch](https://github.com/erf/dart_console/tree/resize).

A bit stuck for now, with the thing mentioned in previous comment.

**Comment by erf** [comment]
Btw. seem like you can get [terminalLines](https://api.dartlang.org/stable/2.6.1/dart-io/Stdout/terminalLines.html) and [terminalColumns](https://api.dartlang.org/stable/2.6.1/dart-io/Stdout/terminalColumns.html) to get width / height.

**Comment by erf** [comment]
@timsneath i figured you can listen to SIGWINCH aka window resize events using [ProcessSignal.sigwinch.watch()](https://api.dart.dev/stable/2.7.2/dart-io/ProcessSignal/sigwinch-constant.html) ( unix only ). ( and also get cols and rows using core dart libs )

i made a very simple [console lib](https://github.com/erf/console) in dart, based on my previous [sta](https://github.com/erf/sta) lib

i was able to get rawmode "light" using:
```
      stdin.echoMode = false;
      stdin.lineMode = false;
```
i do async input using `stdin`

it's lots simpler than your lib, and not meant for serious work, but i was able to play around with it, and remade snake and some other examples :)

**Comment by timsneath** [comment]
Thanks - I'll take a look!
