### ISSUE TITLE
Consider adding italic text style?

### ISSUE THREAD

**Issue by rferrante** [timsneath/dart_console#12]
Would you consider adding 'italic' as a text style? it uses ansi '3' in the same position as 'bold' uses '1'. iTerm supports it, btw.
--Rob

String ansiSetTextStyles(
    {bool bold = false,
    bool underscore = false,
    bool blink = false,
    bool inverted = false,
    bool italic = false}) {
  var styles = <int>[];
  if (bold) styles.add(1);
  if (underscore) styles.add(4);
  if (blink) styles.add(5);
  if (inverted) styles.add(7);
  if (italic) styles.add(3);
  return '\x1b[${styles.join(";")}m';
}

**Comment by timsneath** [comment]
I'm open to it, but my primary reservation is whether italics is [broadly supported in different terminals](https://superuser.com/questions/204743/terminal-that-supports-the-ansi-italic-escape-code/603935)? Unfortunately there's [no way AFAICT to test for terminal support](https://unix.stackexchange.com/questions/228369/how-to-programmatically-check-if-the-terminal-supports-italics)
