### ISSUE TITLE
Not an issue

### ISSUE THREAD

**Issue by glenfordwilliams** [timsneath/dart_console#13]
Hi i'm trying to follow your library to learn a bit more about dart ffi  and i'm curious about this section 

where the unix definition is 

`// 	cc_t            c_cc[NCCS];     /* control chars */`

but you chose to do 
```
  // This replaces c_cc[20]
  @Int8()
  int c_cc0;
  @Int8()
  int c_cc1;
  @Int8()
  int c_cc2;
  @Int8()
  int c_cc3;
  @Int8()
  int c_cc4;
  @Int8()
  int c_cc5;
  @Int8()
  int c_cc6;
  @Int8()
  int c_cc7;
  @Int8()
  int c_cc8;
  @Int8()
  int c_cc9;
  @Int8()
  int c_cc10;
  @Int8()
  int c_cc11;
  @Int8()
  int c_cc12;
  @Int8()
  int c_cc13;
  @Int8()
  int c_cc14;
  @Int8()
  int c_cc15;
  @Int8()
  int c_cc16; // VMIN
  @Int8()
  int c_cc17; // VTIME
  @Int8()
  int c_cc18;
  @Int8()
  int c_cc19;
```

is there a reference anywhere than explains this?
taken from here
https://github.com/timsneath/dart_console/blob/28f333aff8f508d10c0bf8431b54bbb813584cbd/lib/src/ffi/unix/termios.dart#L87

**Comment by timsneath** [comment]
Yeah, this is a workaround for the lack of support for inline arrays (https://github.com/dart-lang/sdk/issues/35763).
