### ISSUE TITLE
PR for multi-line input

### ISSUE THREAD

**Issue by ssaundersla** [timsneath/dart_console#15]
Hi, Tim. Are you open to a pull request? I would like to use your dart_console library in a project I'm starting, but I was hoping for a readline that would handle using the up and down keys to scroll through previous lines. I see from your comment in console.dart ("TODO: Add multi-line input.") that this is an interest of yours as well. I have a local copy with this change if you would like to review it.

**Comment by timsneath** [comment]
Absolutely! I started playing around with implementing multiline myself,
but then got a little distracted by the FFI / Win32 API side of things and
put it down.

I'd love to consider some PRs for this package!
