### ISSUE TITLE
wrong SDK constraint '>=2.4.0 <3.0.0'

### ISSUE THREAD

**Issue by jonasfj** [timsneath/dart_console#2]
As this uses `dart:ffi` it clearly won't work on dart 2.4.0:

https://github.com/timsneath/dart_console/blob/492b876ee16afdf3d67097555ca526b011738434/pubspec.yaml#L7-L8

---

side note, this is still pretty cool :)

**Comment by jonasfj** [comment]
You can reference dev versions in the `sdk` constraint, you'll get a sad score on `pub.dev`, but such is life when publishing for a development version.

**Comment by timsneath** [comment]
Thanks for the catch, @jonasfj. Let me know if this works...

**Comment by timsneath** [comment]
Oh, that's really sad -- fixing that has stopped `dartdoc` from working... not sure if that's better than having the version dependency incorrect.
