### ISSUE TITLE
Methods missing from docs / package on pub.dev

### ISSUE THREAD

**Issue by averynortonsmith** [timsneath/dart_console#20]
It seems that there's a mismatch between the source code and the documentation / examples / code on pub.dev. For example `console.dart` shows a named constructor [Console.scrolling()](https://github.com/timsneath/dart_console/blob/master/lib/src/console.dart#L115), but this is missing from the [documentation](https://pub.dev/documentation/dart_console/latest/dart_console/Console-class.html) and not present in the code downloaded from pub.dev.

Is there a way to resolve this mismatch? I'd love to be able to use the scrollback functionality.

**Comment by timsneath** [comment]
This should now be fixed; sorry, it was just a while between releases.
