### ISSUE TITLE
Type errors in dart_console-0.6.1 on Dart VM version: 2.9.0-17.0.dev.flutter-7e72c9ae7e

### ISSUE THREAD

**Issue by jonahwilliams** [timsneath/dart_console#23]
Probably caused by https://github.com/timsneath/dart_console/commit/ed52d5b722d7a1bcc52bc35d030a0ef381b7754f , though I'm not sure why the type of FillConsoleOutputCharacter changed.

```
../../../../../.pub-cache/hosted/pub.dartlang.org/dart_console-0.6.1/lib/src/ffi/win/termlib-win.dart:90:58: Error: The argument type 'Pointer<Uint32>' can't be assigned to the parameter type 'Pointer<Int32>'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Uint32' is from 'dart:ffi'.
 - 'Int32' is from 'dart:ffi'.
        outputHandle, ' '.codeUnitAt(0), consoleSize, 0, pCharsWritten);
                                                         ^
../../../../../.pub-cache/hosted/pub.dartlang.org/dart_console-0.6.1/lib/src/ffi/win/termlib-win.dart:95:63: Error: The argument type 'Pointer<Uint32>' can't be assigned to the parameter type 'Pointer<Int32>'.
 - 'Pointer' is from 'dart:ffi'.
 - 'Uint32' is from 'dart:ffi'.
 - 'Int32' is from 'dart:ffi'.
        outputHandle, bufferInfo.wAttributes, consoleSize, 0, pCharsWritten);
```

**Comment by jonahwilliams** [comment]
Actually on windows, I'm getting the opposite type error on 0.6.0. 🤦

**Comment by timsneath** [comment]
Hmm... I tightened a couple of the types to indicate their unsigned status in the parent [win32](https://pub.dev/packages/win32) package, but I thought I'd fixed the downstream versions appropriately. I don't have a ton of tests for this hobby project, but I've just uploaded 0.6.2, which bumps the minver for the win32 dependency.

Could you give that a try?

**Comment by jonahwilliams** [comment]
Yeah, I managed to work around this by pinning to `win32: 1.6.3`, I will check out the new 0.6.2 version

**Comment by jonahwilliams** [comment]
Seems to be fixed, thanks @timsneath !
