### ISSUE TITLE
`Console.readLine()` doesn't allow users to paste text into terminal

### ISSUE THREAD

**Issue by mkustermann** [timsneath/dart_console#52]
Normally one can past text into apps running on terminals: Be it a shell or interactive tools e.g. `gdb` one can paste text into the terminal prompt.

Using `package:dart_console`s `Console.readLine()` api this is not possible, instead it will only take the first character and discard the rest of the pasted text. Simple reproduction
```
% dart example/readline_scrolling.dart
>>>
```
and try pasting some text with middle mouse button on linux.

The root cause of that is that `Console.readLine()` is implemented by repeatedly calling `Console.readKey()` which switches in/out of raw mode. The switching in/out of raw mode will cause remaining buffered input to be discarded.

The issue itself can be fixed by this small change
```diff
diff --git a/lib/src/ffi/unix/termlib_unix.dart b/lib/src/ffi/unix/termlib_unix.dart
index 1ef85ef..5d30b5c 100644
--- a/lib/src/ffi/unix/termlib_unix.dart
+++ b/lib/src/ffi/unix/termlib_unix.dart
@@ -52,7 +52,7 @@ class TermLibUnix implements TermLib {
       ..ref.c_ispeed = origTermIOS.c_ispeed
       ..ref.c_oflag = origTermIOS.c_ospeed;
 
-    tcsetattr(STDIN_FILENO, TCSAFLUSH, newTermIOSPointer);
+    tcsetattr(STDIN_FILENO, TCSADRAIN, newTermIOSPointer);
 
     calloc.free(newTermIOSPointer);
   }
@@ -60,7 +60,7 @@ class TermLibUnix implements TermLib {
   @override
   void disableRawMode() {
     if (nullptr == _origTermIOSPointer.cast()) return;
-    tcsetattr(STDIN_FILENO, TCSAFLUSH, _origTermIOSPointer);
+    tcsetattr(STDIN_FILENO, TCSADRAIN, _origTermIOSPointer);
   }
 
   TermLibUnix() {
```

/cc @timsneath Do you think this is the right fix? (I'd really like to have the copy&paste into command prompt working - it's such an important use case)

**Comment by timsneath** [comment]
That's interesting. The drain behavior matches Windows, so this does look like the right fix.

**Comment by timsneath** [comment]
Hmm... unfortunately this seems to break `kilo.dart`, since readKey no longer reads just one key at a time. Looks like `TCSANOW` might be the right option...
