### ISSUE TITLE
Game: Run Console in Flutter Web?

### ISSUE THREAD

**Issue by xErik** [timsneath/dart_console#62]
Hello,

I develop a roguelike game that runs in a Console.

To showcase the game I would like to embedd the Console in Flutter Web.

I realize that this is probably not possible due to technical limitations.

Or could it be done?

Thank you.

**Comment by domesticmouse** [comment]
Flutter has a variety of ways of displaying text on the screen. I'd suggest asking a question on StackOverflow. 

This package is about managing the console from a dart command line program, not emulating a command line experience in a Flutter program.
