### ISSUE TITLE
Pasting clipboard content to readLine pastes only first character

### ISSUE THREAD

**Issue by bryanso** [timsneath/dart_console#64]
Tested in MacOS (no other O/S available for me).  Create a simple Dart console app.  Use console.readLine() to read a line.

Pasting clipboard content (%V in MacOS) doesn't work as expected.  Only the first character would be pasted.   I tried to write my own loop to use console.readKey() to get a full line.  Same buggy behavior.

Using Dart's own stdin.readByteSync() in a loop to get a line does not have the same problem.  %V works perfectly in that case.

**Comment by bryanso** [comment]
It has to do with setting rawMode = true inside readkey() 

If we remove it but set rawMode in the beginning of readLine() then unset it before returning, then pasting works fine.

**Comment by bsutton** [comment]
I've taken over maintenance of dart console.

Happy to accept a pr.

**Comment by domesticmouse** [comment]
@bsutton Can you link to your github repo? The repo linked from https://pub.dev/packages/dart_console is https://github.com/onepub.dev/dart_console which is 404'ing.

**Comment by bryanso** [comment]
> I've taken over maintenance of dart console. Happy to accept a pr.
> […](#)
>
Happy to work on it.  Give me some time because readKey() is public.  We need to make sure any code calling readKey() is not broken.

**Comment by bsutton** [comment]
I've published 4.0.2 which has the correct repository url.

Thanks for reporting it.

**Comment by bsutton** [comment]
> Happy to work on it. Give me some time because readKey() is public. We
need to make sure any code calling readKey() is not broken.

Let me know when it's ready. Appreciate the care.

**Comment by bryanso** [comment]
bsutton, would you mind checking if this has already been fixed but not merged?

https://github.com/timsneath/dart_console/pull/57

The comment in the above indicates the same problem as I reported.
(I'm checking my lib.  I might have an older version... stay tuned.)

**Comment by bryanso** [comment]
I'm closing this.  I had an old dart version.  After upgrading I am able to use dart_console 1.2.0.  Problem has been fixed already.  My bad.

**Comment by bsutton** [comment]
No problem.
