### ISSUE TITLE
NOTE: New issues should be raised against: https://onepub-dev/dart_console

### ISSUE THREAD

**Issue by bsutton** [timsneath/dart_console#65]
Tim has asked me to take over maintenance of the dart_console project.

All future work will  be done via:

 https://onepub-dev/dart_console

So don't raise any new issues here.

**Comment by shreyashsaitwal** [comment]
Is this legitimate, @timsneath?

**Comment by timsneath** [comment]
Yes. @bsutton kindly took ownership of `dart_console` after [I joined Apple](https://x.com/timsneath/status/1681351354676285441).
